repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        args: [--fix]
        always_run: true
      - id: ruff-format
        always_run: true
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.400
    hooks:
      - id: pyright
        always_run: true
  - repo: local
    hooks:
      - id: generate-cli-docs
        name: Generate Typer CLI docs
        entry: typer netwatcher.main utils docs --name netwatcher --output DOCS.md --title NetWatcher
        language: system
        pass_filenames: false
        always_run: true
