[project]
name = "remote-ip-geo-info"
version = "0.1.0"
description = """
A Python CLI tool that retrieves remote IP addresses your system is connected to, and provides their geographic location
and associated business information, excluding local network connections.
"""
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
